experiment_name: 'time'
device: 'cuda:0'
output_folder: ./outputs/
n_steps_interval: [64, 64]
split_rate_interval: ~ #[60, 90]
test_frequency: 1
logging_level: DEBUG
emoji: 🦋
model:
  use_coords: False  # whether to pass meshgrid as a feature
  random_spawn: False  # randomly select initial cell coordinates
  stochastic_prob: 0.5
  norm_kernel: False
  interm_dim: 128
train:
  batch_size: 4
  num_epochs: 50
optim:
  milestones: [2000]
  gamma: 0.1
  lr: 0.00001
  grad_clip: 20
