experiment_name: 'time'
device: 'cuda:0'
output_folder: ./outputs/
n_steps_interval: [60, 61]
split_rate_interval: ~ #[60, 90]
test_frequency: 100
logging_level: DEBUG
emoji: 🥨
model:
  use_coords: False  # whether to pass meshgrid as a feature
  random_spawn: False  # randomly select initial cell coordinates
  stochastic_prob: 1
train:
  batch_size: 1
  num_epochs: 8000
optim:
  milestones: [2000]
  gamma: 0.1
  lr: 0.002
  grad_clip: 10

