experiment_name: 'time'
device: 'cuda:0'
output_folder: ./outputs/
n_steps_interval: [64, 92]
split_rate_interval: ~ #[60, 90]
test_frequency: 100
logging_level: DEBUG
data:
  pad: 16
  target_size: 40
  emoji: 🦋 
model:
  use_coords: False  # whether to pass meshgrid as a feature
  random_spawn: True  # randomly select initial cell coordinates
  stochastic_prob: 0.5
  norm_kernel: False
  interm_dim: 128
  bias: True
train:
  batch_size: 4
  num_epochs: 8000
optim:
  milestones: [2000]
  gamma: 0.1
  lr: 0.002
  grad_clip: 20
