experiment_name: 'time'
device: 'cuda:0'
output_folder: ./outputs/
n_steps_interval: [60, 90]
split_rate_interval: ~ #[60, 90]
test_frequency: 500
logging_level: DEBUG
model:
  use_coords: True  # whether to pass meshgrid as a feature
  random_spawn: False  # randomly select initial cell coordinates
  stochastic_prob: 0.5
train:
  batch_size: 4
  num_epochs: 8000
optim:
  milestones: [2000]
  gamma: 0.1
  lr: 0.0005
  grad_clip: 200

