experiment_name: 'time'
device: 'cuda:0'
output_folder: ./outputs/
n_steps_interval: [180, 240]
split_rate_interval: [60, 90]
test_frequency: 100
logging_level: DEBUG
model:
  use_coords: True  # whether to pass meshgrid as a feature
  random_spawn: False  # randomly select initial cell coordinates
  stochastic_prob: 0.1
train:
  batch_size: 4
  num_epochs: 2000
optim:
  milestones: [500, 1000, 1500, 2000]
  gamma: 0.5
  lr: 0.001

